### ISSUE TITLE
can you success build? s

### ISSUE THREAD

**Issue by Lin3er** [K3rnel-Dev/VenomRat-SourceCode#2]
can you success build? s

**Comment by K3rnel-Dev** [comment]
Hello!, when I managed to bypass the protection, I changed several actions in dnspy, which opened access to the application without hvid and other bindings, and I also managed to extract the source code using the dnspy utility, but I don’t know about successful compilation because sometimes dnspy gives incorrect results that prevent the project from being compiled.
