### ISSUE TITLE
Has virus and too many backdoors, hole github delete your account

### ISSUE THREAD

**Issue by adevnos** [K3rnel-Dev/VenomRat-SourceCode#5]

**Comment by K3rnel-Dev** [comment]
Are you stuped or no????
i say:
"Please run this app in isolation from your computer, I'm not sure that this app is all clean because I could bypass the protection against venomrat, USE ONLY VM OR DEDICATED SERVER!!!"

I'm not saying to run the application on a computer, I bypassed venomrat protection and got the source code through dnspy, and I'm not sure that the venomrat developer didn't put viruses in there, so I recommend everyone to test it on a virtual machine. Just as I am not responsible for your actions, this code was provided purely for study by malware-analysts
